version: '3.0'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./getssl/data/nginx:/etc/nginx
      - ./getssl/data/certbot/conf:/etc/letsencrypt
      - ./getssl/data/certbot/www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-tier
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./getssl/data/certbot/conf:/etc/letsencrypt
      - ./getssl/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-tier

#  redis:
#    image: redis
#    command: redis-server --requirepass admin --port 6379
#    restart: always
#    networks:
#      - app-tier
#    ports:
#      - 6379:6379
#  api:
#    build: .
#    container_name: "pass-analytics-api"
#    ports:
#      - "8000:8000"
#    volumes:
#      - './:/home/pass-analytics-api'
#    working_dir: /home/pass-analytics-api
#    command: uvicorn main:app --host 0.0.0.0
#    networks:
#      - app-tier

networks:
  app-tier:
    driver: bridge